# Generated by Django 3.2.7 on 2021-09-27 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Adoption', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='adoption',
            name='mainimage10',
            field=models.ImageField(default=11, upload_to='Adoption'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='adoption',
            name='mainimage11',
            field=models.ImageField(default=1, upload_to='Adoption'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='adoption',
            name='mainimage12',
            field=models.ImageField(default=1, upload_to='Adoption'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='adoption',
            name='mainimage2',
            field=models.ImageField(default=0, upload_to='Adoption'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='adoption',
            name='mainimage3',
            field=models.ImageField(default=1, upload_to='Adoption'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='adoption',
            name='mainimage4',
            field=models.ImageField(default=11, upload_to='Adoption'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='adoption',
            name='mainimage5',
            field=models.ImageField(default=1, upload_to='Adoption'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='adoption',
            name='mainimage6',
            field=models.ImageField(default=1, upload_to='Adoption'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='adoption',
            name='mainimage7',
            field=models.ImageField(default=1, upload_to='Adoption'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='adoption',
            name='mainimage8',
            field=models.ImageField(default=1, upload_to='Adoption'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='adoption',
            name='mainimage9',
            field=models.ImageField(default=1, upload_to='Adoption'),
            preserve_default=False,
        ),
    ]
