# Generated by Django 3.2.7 on 2021-09-27 14:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Adoption', '0002_auto_20210927_1816'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Adoption',
            new_name='Adoptions',
        ),
    ]
